### PR TITLE
introducing bors bot

### PR DESCRIPTION
**Pull request by kinggoesgaming**

### CODE REVIEW

**Comment by kinggoesgaming** [comment]
bors: ping

**Comment by kinggoesgaming** [comment]
@mokeyish when merging please use one of the following instead of hitting the merge button:

`bors: r+`
`bors r+`

**Comment by mokeyish** [comment]
bors: r+

**Comment by mokeyish** [comment]
bors: ping

**Review by Dylan-DPC-zz — APPROVED** [review]

**Comment by Dylan-DPC-zz** [comment]
bors: r+

**Pull request merged**
